// =============================================================
// Portal Condominio · Titularidad — datos mock
// Cubre los casos reales de la sección 3 del brief. Sin datos reales.
// El desarrollo es "Margot" explícito (nunca id_proyecto=1 por defecto).
// =============================================================
import type {
  Campo,
  Cruce,
  DocumentoExpediente,
  EstadoValidacion,
  SolicitudTitularidad,
} from "./types";

const DUENO_ORIGINAL = "Hevi Holding S.A. de C.V.";

function c<T>(
  valor: T | null,
  estado: EstadoValidacion = "validado",
  idDocumentoFuente: string | null = null,
): Campo<T> {
  return { valor, estado, idDocumentoFuente };
}

// Identificación (física) genérica validada.
function docIdentificacion(id: string, nombre: string): DocumentoExpediente {
  return {
    id,
    tipo: "identificacion",
    nombreArchivo: "INE_frente_reverso.pdf",
    urlMock: "mock://doc/ine",
    requerimiento: "cargado",
    estado: "validado",
    vigencia: "vigente",
    datosExtraidos: {
      nombre: c(nombre, "validado", id),
      vigencia: c("2029", "validado", id),
    },
  };
}

export const MOCK_SOLICITUDES: SolicitudTitularidad[] = [
  // 1) Física, contado, completo, cruces verdes → Nivel 2 limpio
  {
    id: "TIT-000001",
    tipoPersona: "fisica",
    nombreODireccionRazonSocial: "María Fernanda Gómez Ruiz",
    rfc: c("GORM880412H23", "validado", "doc-1-esc"),
    curp: c("GORM880412MJCMZR04", "validado", "doc-1-curp"),
    correo: "mf.gomez@gmail.com",
    telefono: "+52 33 1122 3344",
    desarrollo: "Margot",
    unidad: "#201",
    folioReal: c("1234567", "validado", "doc-1-rpp"),
    direccion: "Av. Chapultepec 480, Piso 2, Guadalajara, Jal.",
    modelo: "Breath",
    duenoOriginalRegistrado: DUENO_ORIGINAL,
    contextoCompra: "contado",
    antiguedad: "normal",
    documentos: [
      docIdentificacion("doc-1-id", "María Fernanda Gómez Ruiz"),
      {
        id: "doc-1-esc",
        tipo: "escritura",
        nombreArchivo: "Escritura_publica_45231.pdf",
        urlMock: "mock://doc/escritura",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: {
          adquiriente: c("María Fernanda Gómez Ruiz", "validado", "doc-1-esc"),
          enajenante: c(DUENO_ORIGINAL, "validado", "doc-1-esc"),
          folioReal: c("1234567", "validado", "doc-1-esc"),
        },
      },
      {
        id: "doc-1-rpp",
        tipo: "certificado_rpp",
        nombreArchivo: "Certificado_RPP_1234567.pdf",
        urlMock: "mock://doc/rpp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "vigente",
        datosExtraidos: {
          titular: c("María Fernanda Gómez Ruiz", "validado", "doc-1-rpp"),
          folioReal: c("1234567", "validado", "doc-1-rpp"),
          gravamen: c("Sin gravámenes", "validado", "doc-1-rpp"),
        },
      },
      {
        id: "doc-1-predial",
        tipo: "predial",
        nombreArchivo: "Predial_2025.pdf",
        urlMock: "mock://doc/predial",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "vigente",
        datosExtraidos: { titular: c("María Fernanda Gómez Ruiz", "validado", "doc-1-predial") },
      },
      {
        id: "doc-1-curp",
        tipo: "curp_constancia",
        nombreArchivo: "Constancia_CURP.pdf",
        urlMock: "mock://doc/curp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: { curp: c("GORM880412MJCMZR04", "validado", "doc-1-curp") },
      },
    ],
    cruces: [
      {
        id: "x1-cad",
        etiqueta: "Cadena de dominio (enajenante escritura vs. dueño original SOZU)",
        resultado: "verde",
        detalle: "Enajenante en escritura: Hevi Holding S.A. de C.V. = dueño original registrado.",
        esCadenaDominio: true,
      },
      { id: "x1-id", etiqueta: "Nombre ID = Escritura = RPP", resultado: "verde", detalle: "Coinciden en los tres documentos." },
      { id: "x1-folio", etiqueta: "Folio real Escritura = RPP", resultado: "verde", detalle: "1234567 en ambos." },
      { id: "x1-rpp", etiqueta: "Certificado RPP vigente", resultado: "verde", detalle: "Emitido hace 21 días." },
    ],
    semaforoAgregado: "verde",
    gravamen: { existe: false, acreedor: null },
    verificacionRegistral: "verificado",
    cadenaDominioConfirmada: true,
    estado: "en_revision",
    nivelSolicitado: 2,
    nivelOtorgado: null,
    areaAsignada: "legal",
    fechaCreacion: "2026-07-08T10:00:00.000Z",
    diasEnCola: 6,
    auditoria: [
      { id: "a1-1", timestamp: "2026-07-08T10:00:00.000Z", usuario: "Sistema", accion: "Solicitud recibida", detalle: "Expediente cargado por el solicitante." },
      { id: "a1-2", timestamp: "2026-07-09T09:15:00.000Z", usuario: "L. Ramírez (Legal)", accion: "Verificación registral", detalle: "RPP confirmado por folio real 1234567." },
    ],
  },

  // 2) Física, crédito hipotecario → gravamen BBVA (no bloquea Nivel 1)
  {
    id: "TIT-000002",
    tipoPersona: "fisica",
    nombreODireccionRazonSocial: "Jorge Alberto Núñez Salas",
    rfc: c("NUSJ900101A11", "validado", "doc-2-esc"),
    curp: c("NUSJ900101HJCXLR09", "validado", "doc-2-curp"),
    correo: "janunez@outlook.com",
    telefono: "+52 33 2233 4455",
    desarrollo: "Margot",
    unidad: "#404",
    folioReal: c("2234891", "validado", "doc-2-rpp"),
    direccion: "Av. Chapultepec 480, Piso 4, Guadalajara, Jal.",
    modelo: "Heart",
    duenoOriginalRegistrado: DUENO_ORIGINAL,
    contextoCompra: "credito_hipotecario",
    antiguedad: "normal",
    documentos: [
      docIdentificacion("doc-2-id", "Jorge Alberto Núñez Salas"),
      {
        id: "doc-2-esc",
        tipo: "escritura",
        nombreArchivo: "Escritura_publica_46012.pdf",
        urlMock: "mock://doc/escritura",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: {
          adquiriente: c("Jorge Alberto Núñez Salas", "validado", "doc-2-esc"),
          enajenante: c(DUENO_ORIGINAL, "validado", "doc-2-esc"),
          gravamen: c("Hipoteca a favor de BBVA México", "validado", "doc-2-esc"),
        },
      },
      {
        id: "doc-2-rpp",
        tipo: "certificado_rpp",
        nombreArchivo: "Certificado_RPP_2234891.pdf",
        urlMock: "mock://doc/rpp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "vigente",
        datosExtraidos: {
          titular: c("Jorge Alberto Núñez Salas", "validado", "doc-2-rpp"),
          gravamen: c("Hipoteca inscrita · BBVA México", "validado", "doc-2-rpp"),
        },
      },
      {
        id: "doc-2-curp",
        tipo: "curp_constancia",
        nombreArchivo: "Constancia_CURP.pdf",
        urlMock: "mock://doc/curp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: { curp: c("NUSJ900101HJCXLR09", "validado", "doc-2-curp") },
      },
    ],
    cruces: [
      {
        id: "x2-cad",
        etiqueta: "Cadena de dominio (enajenante escritura vs. dueño original SOZU)",
        resultado: "verde",
        detalle: "Enajenante: Hevi Holding S.A. de C.V. = dueño original registrado.",
        esCadenaDominio: true,
      },
      { id: "x2-id", etiqueta: "Nombre ID = Escritura = RPP", resultado: "verde", detalle: "Coinciden." },
      { id: "x2-grav", etiqueta: "Gravamen declarado = RPP", resultado: "verde", detalle: "Hipoteca BBVA presente en escritura y RPP (consistente)." },
    ],
    semaforoAgregado: "verde",
    gravamen: { existe: true, acreedor: "BBVA México" },
    verificacionRegistral: "en_gestion",
    cadenaDominioConfirmada: null,
    estado: "en_revision",
    nivelSolicitado: 2,
    nivelOtorgado: null,
    areaAsignada: "legal",
    fechaCreacion: "2026-07-11T14:30:00.000Z",
    diasEnCola: 3,
    auditoria: [
      { id: "a2-1", timestamp: "2026-07-11T14:30:00.000Z", usuario: "Sistema", accion: "Solicitud recibida", detalle: "Compra con crédito hipotecario (BBVA)." },
    ],
  },

  // 3) Compra reciente (<6m) → predial a nombre anterior, RPP en trámite. Ámbar.
  {
    id: "TIT-000003",
    tipoPersona: "fisica",
    nombreODireccionRazonSocial: "Ana Lucía Prieto Vega",
    rfc: c("PIVA950623B45", "validado", "doc-3-esc"),
    curp: c("PIVA950623MJCRGN02", "validado", "doc-3-curp"),
    correo: "ana.prieto@gmail.com",
    telefono: "+52 33 3344 5566",
    desarrollo: "Margot",
    unidad: "#702",
    folioReal: c("3391002", "en_revision", "doc-3-esc"),
    direccion: "Av. Chapultepec 480, Piso 7, Guadalajara, Jal.",
    modelo: "Joy",
    duenoOriginalRegistrado: DUENO_ORIGINAL,
    contextoCompra: "contado",
    antiguedad: "reciente",
    documentos: [
      docIdentificacion("doc-3-id", "Ana Lucía Prieto Vega"),
      {
        id: "doc-3-esc",
        tipo: "escritura",
        nombreArchivo: "Escritura_publica_47788.pdf",
        urlMock: "mock://doc/escritura",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: {
          adquiriente: c("Ana Lucía Prieto Vega", "validado", "doc-3-esc"),
          enajenante: c(DUENO_ORIGINAL, "validado", "doc-3-esc"),
        },
      },
      {
        id: "doc-3-predial",
        tipo: "predial",
        nombreArchivo: "Predial_2025.pdf",
        urlMock: "mock://doc/predial",
        requerimiento: "cargado",
        estado: "por_confirmar",
        vigencia: "vigente",
        datosExtraidos: {
          // Predial aún a nombre del propietario anterior — normal en compra reciente.
          titular: c("Hevi Holding S.A. de C.V.", "por_confirmar", "doc-3-predial"),
        },
      },
      {
        id: "doc-3-rpp",
        tipo: "certificado_rpp",
        nombreArchivo: "(pendiente — RPP en trámite)",
        urlMock: "mock://doc/rpp-faltante",
        requerimiento: "pendiente",
        estado: "en_revision",
        vigencia: "no_aplica",
        datosExtraidos: {},
      },
      {
        id: "doc-3-curp",
        tipo: "curp_constancia",
        nombreArchivo: "Constancia_CURP.pdf",
        urlMock: "mock://doc/curp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: { curp: c("PIVA950623MJCRGN02", "validado", "doc-3-curp") },
      },
    ],
    cruces: [
      {
        id: "x3-cad",
        etiqueta: "Cadena de dominio (enajenante escritura vs. dueño original SOZU)",
        resultado: "verde",
        detalle: "Enajenante = dueño original registrado.",
        esCadenaDominio: true,
      },
      { id: "x3-predial", etiqueta: "Titular predial = solicitante", resultado: "ambar", detalle: "Predial aún figura a nombre del propietario anterior (compra reciente, < 6 meses)." },
      { id: "x3-rpp", etiqueta: "Certificado RPP disponible", resultado: "ambar", detalle: "RPP en trámite; folio real por confirmar con verificación registral." },
    ],
    semaforoAgregado: "ambar",
    gravamen: { existe: false, acreedor: null },
    verificacionRegistral: "no_iniciada",
    cadenaDominioConfirmada: null,
    estado: "en_revision",
    nivelSolicitado: 1,
    nivelOtorgado: null,
    areaAsignada: "escrituracion",
    fechaCreacion: "2026-07-13T08:00:00.000Z",
    diasEnCola: 1,
    auditoria: [
      { id: "a3-1", timestamp: "2026-07-13T08:00:00.000Z", usuario: "Sistema", accion: "Solicitud recibida", detalle: "Compra reciente; predial a nombre anterior y RPP en trámite." },
    ],
  },

  // 4) Bandera roja de cadena de dominio (control anti-fraude central)
  {
    id: "TIT-000004",
    tipoPersona: "fisica",
    nombreODireccionRazonSocial: "Roberto Carlos Méndez Lara",
    rfc: c("MELR820917C88", "en_revision", "doc-4-esc"),
    curp: c("MELR820917HJCNRB07", "validado", "doc-4-curp"),
    correo: "rc.mendez@gmail.com",
    telefono: "+52 33 4455 6677",
    desarrollo: "Margot",
    unidad: "#1103",
    folioReal: c("4410233", "en_revision", "doc-4-esc"),
    direccion: "Av. Chapultepec 480, Piso 11, Guadalajara, Jal.",
    modelo: "Kind",
    duenoOriginalRegistrado: DUENO_ORIGINAL,
    contextoCompra: "contado",
    antiguedad: "normal",
    documentos: [
      docIdentificacion("doc-4-id", "Roberto Carlos Méndez Lara"),
      {
        id: "doc-4-esc",
        tipo: "escritura",
        nombreArchivo: "Escritura_publica_SN.pdf",
        urlMock: "mock://doc/escritura",
        requerimiento: "cargado",
        estado: "en_revision",
        vigencia: "no_aplica",
        datosExtraidos: {
          adquiriente: c("Roberto Carlos Méndez Lara", "en_revision", "doc-4-esc"),
          // Enajenante NO coincide con el dueño original registrado por SOZU.
          enajenante: c("Inmobiliaria del Valle S.A.", "rechazado", "doc-4-esc"),
        },
      },
      {
        id: "doc-4-curp",
        tipo: "curp_constancia",
        nombreArchivo: "Constancia_CURP.pdf",
        urlMock: "mock://doc/curp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: { curp: c("MELR820917HJCNRB07", "validado", "doc-4-curp") },
      },
    ],
    cruces: [
      {
        id: "x4-cad",
        etiqueta: "Cadena de dominio (enajenante escritura vs. dueño original SOZU)",
        resultado: "rojo",
        detalle:
          "Enajenante en escritura: 'Inmobiliaria del Valle S.A.' ≠ dueño original registrado: 'Hevi Holding S.A. de C.V.'. Requiere revisión legal antes de cualquier decisión.",
        esCadenaDominio: true,
      },
      { id: "x4-id", etiqueta: "Nombre ID = Escritura", resultado: "verde", detalle: "Adquiriente coincide con la identificación." },
    ],
    semaforoAgregado: "rojo",
    gravamen: { existe: false, acreedor: null },
    verificacionRegistral: "no_iniciada",
    cadenaDominioConfirmada: false,
    estado: "nueva",
    nivelSolicitado: 2,
    nivelOtorgado: null,
    areaAsignada: "legal",
    fechaCreacion: "2026-07-02T11:00:00.000Z",
    diasEnCola: 12,
    auditoria: [
      { id: "a4-1", timestamp: "2026-07-02T11:00:00.000Z", usuario: "Sistema", accion: "Solicitud recibida", detalle: "Cruce automático marcó bandera roja de cadena de dominio." },
    ],
  },

  // 5) Persona moral — representante legal, poder pendiente de revisión legal
  {
    id: "TIT-000005",
    tipoPersona: "moral",
    nombreODireccionRazonSocial: "Grupo Residencial Poniente S.A. de C.V.",
    rfc: c("GRP180325AB2", "validado", "doc-5-constancia"),
    razonSocial: c("Grupo Residencial Poniente S.A. de C.V.", "validado", "doc-5-acta"),
    representanteLegal: {
      nombre: c("Silvia Torres Camacho", "validado", "doc-5-poder"),
      curp: c("TOCS750210MJCRM24", "validado", "doc-5-id-rep"),
    },
    correo: "admin@grupoponiente.mx",
    telefono: "+52 33 5566 7788",
    desarrollo: "Margot",
    unidad: "#905",
    folioReal: c("5502114", "validado", "doc-5-rpp"),
    direccion: "Av. Chapultepec 480, Piso 9, Guadalajara, Jal.",
    modelo: "Soft",
    duenoOriginalRegistrado: DUENO_ORIGINAL,
    contextoCompra: "contado",
    antiguedad: "normal",
    documentos: [
      {
        id: "doc-5-constancia",
        tipo: "constancia_moral",
        nombreArchivo: "Constancia_situacion_fiscal.pdf",
        urlMock: "mock://doc/constancia-moral",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "vigente",
        datosExtraidos: {
          razonSocial: c("Grupo Residencial Poniente S.A. de C.V.", "validado", "doc-5-constancia"),
          rfc: c("GRP180325AB2", "validado", "doc-5-constancia"),
        },
      },
      {
        id: "doc-5-acta",
        tipo: "acta_constitutiva",
        nombreArchivo: "Acta_constitutiva.pdf",
        urlMock: "mock://doc/acta",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: { objeto: c("Adquisición y administración de inmuebles", "validado", "doc-5-acta") },
      },
      {
        id: "doc-5-poder",
        tipo: "poder",
        nombreArchivo: "Poder_notarial.pdf",
        urlMock: "mock://doc/poder",
        requerimiento: "cargado",
        estado: "en_revision",
        vigencia: "por_vencer",
        datosExtraidos: {
          apoderado: c("Silvia Torres Camacho", "validado", "doc-5-poder"),
          facultades: c("Actos de administración y dominio (a confirmar por legal)", "por_confirmar", "doc-5-poder"),
        },
      },
      {
        id: "doc-5-id-rep",
        tipo: "id_representante",
        nombreArchivo: "INE_representante.pdf",
        urlMock: "mock://doc/ine-rep",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "vigente",
        datosExtraidos: { nombre: c("Silvia Torres Camacho", "validado", "doc-5-id-rep") },
      },
      {
        id: "doc-5-rpp",
        tipo: "certificado_rpp",
        nombreArchivo: "Certificado_RPP_5502114.pdf",
        urlMock: "mock://doc/rpp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "vigente",
        datosExtraidos: {
          titular: c("Grupo Residencial Poniente S.A. de C.V.", "validado", "doc-5-rpp"),
        },
      },
    ],
    cruces: [
      {
        id: "x5-cad",
        etiqueta: "Cadena de dominio (enajenante escritura vs. dueño original SOZU)",
        resultado: "verde",
        detalle: "Enajenante = dueño original registrado.",
        esCadenaDominio: true,
      },
      { id: "x5-razon", etiqueta: "Razón social Constancia = RPP", resultado: "verde", detalle: "Coinciden." },
      { id: "x5-poder", etiqueta: "Poder con facultades", resultado: "ambar", detalle: "Facultades de dominio pendientes de revisión legal (no es OCR)." },
    ],
    semaforoAgregado: "ambar",
    gravamen: { existe: false, acreedor: null },
    verificacionRegistral: "en_gestion",
    poderConFacultadesDominio: null,
    cadenaDominioConfirmada: null,
    estado: "en_revision",
    nivelSolicitado: 2,
    nivelOtorgado: null,
    areaAsignada: "legal",
    fechaCreacion: "2026-07-05T16:00:00.000Z",
    diasEnCola: 9,
    auditoria: [
      { id: "a5-1", timestamp: "2026-07-05T16:00:00.000Z", usuario: "Sistema", accion: "Solicitud recibida", detalle: "Persona moral; poder pendiente de revisión legal." },
    ],
  },

  // 6) Certificado RPP con baja confianza OCR
  {
    id: "TIT-000006",
    tipoPersona: "fisica",
    nombreODireccionRazonSocial: "Diego Armando Salinas Peña",
    rfc: c("SAPD910530D33", "por_confirmar", "doc-6-rpp"),
    curp: c("SAPD910530HJCLXG05", "validado", "doc-6-curp"),
    correo: "diego.salinas@gmail.com",
    telefono: "+52 33 6677 8899",
    desarrollo: "Margot",
    unidad: "#308",
    folioReal: c("6612900", "por_confirmar", "doc-6-rpp"),
    direccion: "Av. Chapultepec 480, Piso 3, Guadalajara, Jal.",
    modelo: "Breath",
    duenoOriginalRegistrado: DUENO_ORIGINAL,
    contextoCompra: "contado",
    antiguedad: "normal",
    documentos: [
      docIdentificacion("doc-6-id", "Diego Armando Salinas Peña"),
      {
        id: "doc-6-rpp",
        tipo: "certificado_rpp",
        nombreArchivo: "Certificado_RPP_escaneado.pdf",
        urlMock: "mock://doc/rpp",
        requerimiento: "cargado",
        estado: "por_confirmar",
        vigencia: "vigente",
        datosExtraidos: {
          titular: c("Diego A. Salinas P.", "por_confirmar", "doc-6-rpp"),
          folioReal: c("6612900", "por_confirmar", "doc-6-rpp"),
          gravamen: c("(ilegible)", "por_confirmar", "doc-6-rpp"),
        },
      },
      {
        id: "doc-6-curp",
        tipo: "curp_constancia",
        nombreArchivo: "Constancia_CURP.pdf",
        urlMock: "mock://doc/curp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: { curp: c("SAPD910530HJCLXG05", "validado", "doc-6-curp") },
      },
    ],
    cruces: [
      {
        id: "x6-cad",
        etiqueta: "Cadena de dominio (enajenante escritura vs. dueño original SOZU)",
        resultado: "ambar",
        detalle: "Enajenante ilegible por baja confianza OCR; requiere confirmación humana.",
        esCadenaDominio: true,
      },
      { id: "x6-ocr", etiqueta: "Confianza de extracción OCR", resultado: "ambar", detalle: "Varios campos del RPP marcados 'por confirmar' (documento escaneado de baja calidad)." },
    ],
    semaforoAgregado: "ambar",
    gravamen: { existe: false, acreedor: null },
    verificacionRegistral: "no_iniciada",
    cadenaDominioConfirmada: null,
    estado: "en_revision",
    nivelSolicitado: 1,
    nivelOtorgado: null,
    areaAsignada: "administracion",
    fechaCreacion: "2026-07-10T12:00:00.000Z",
    diasEnCola: 4,
    auditoria: [
      { id: "a6-1", timestamp: "2026-07-10T12:00:00.000Z", usuario: "Sistema", accion: "Solicitud recibida", detalle: "OCR de baja confianza en certificado RPP." },
    ],
  },

  // 7) Certificado RPP expirado (> 90 días)
  {
    id: "TIT-000007",
    tipoPersona: "fisica",
    nombreODireccionRazonSocial: "Patricia Elena Vargas Mora",
    rfc: c("VAMP870714E77", "validado", "doc-7-esc"),
    curp: c("VAMP870714MJCRRT01", "validado", "doc-7-curp"),
    correo: "pativargas@gmail.com",
    telefono: "+52 33 7788 9900",
    desarrollo: "Margot",
    unidad: "#1502",
    folioReal: c("7701455", "validado", "doc-7-rpp"),
    direccion: "Av. Chapultepec 480, Piso 15, Guadalajara, Jal.",
    modelo: "Heart",
    duenoOriginalRegistrado: DUENO_ORIGINAL,
    contextoCompra: "contado",
    antiguedad: "normal",
    documentos: [
      docIdentificacion("doc-7-id", "Patricia Elena Vargas Mora"),
      {
        id: "doc-7-esc",
        tipo: "escritura",
        nombreArchivo: "Escritura_publica_44120.pdf",
        urlMock: "mock://doc/escritura",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: {
          adquiriente: c("Patricia Elena Vargas Mora", "validado", "doc-7-esc"),
          enajenante: c(DUENO_ORIGINAL, "validado", "doc-7-esc"),
        },
      },
      {
        id: "doc-7-rpp",
        tipo: "certificado_rpp",
        nombreArchivo: "Certificado_RPP_2025_vencido.pdf",
        urlMock: "mock://doc/rpp",
        requerimiento: "cargado",
        estado: "expirado",
        vigencia: "expirado",
        datosExtraidos: {
          titular: c("Patricia Elena Vargas Mora", "validado", "doc-7-rpp"),
          emision: c("Emitido hace 118 días", "validado", "doc-7-rpp"),
        },
        motivoRechazo: "Certificado con más de 90 días de antigüedad.",
      },
      {
        id: "doc-7-curp",
        tipo: "curp_constancia",
        nombreArchivo: "Constancia_CURP.pdf",
        urlMock: "mock://doc/curp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: { curp: c("VAMP870714MJCRRT01", "validado", "doc-7-curp") },
      },
    ],
    cruces: [
      {
        id: "x7-cad",
        etiqueta: "Cadena de dominio (enajenante escritura vs. dueño original SOZU)",
        resultado: "verde",
        detalle: "Enajenante = dueño original registrado.",
        esCadenaDominio: true,
      },
      { id: "x7-rpp", etiqueta: "Certificado RPP vigente", resultado: "rojo", detalle: "Certificado expirado (118 días). Se requiere uno reciente (< 90 días)." },
    ],
    semaforoAgregado: "rojo",
    gravamen: { existe: false, acreedor: null },
    verificacionRegistral: "no_iniciada",
    cadenaDominioConfirmada: null,
    estado: "en_revision",
    nivelSolicitado: 2,
    nivelOtorgado: null,
    areaAsignada: "escrituracion",
    fechaCreacion: "2026-07-06T09:00:00.000Z",
    diasEnCola: 8,
    auditoria: [
      { id: "a7-1", timestamp: "2026-07-06T09:00:00.000Z", usuario: "Sistema", accion: "Solicitud recibida", detalle: "Certificado RPP expirado detectado por vigencia." },
    ],
  },

  // 8) Ya en info_solicitada (se pidió más documentación)
  {
    id: "TIT-000008",
    tipoPersona: "fisica",
    nombreODireccionRazonSocial: "Héctor Iván Ramírez Cuevas",
    rfc: c("RACH930822F22", "validado", "doc-8-id"),
    curp: c("RACH930822HJCMVC03", "validado", "doc-8-curp"),
    correo: "hector.ramirez@gmail.com",
    telefono: "+52 33 8899 0011",
    desarrollo: "Margot",
    unidad: "#606",
    folioReal: c("8830771", "en_revision", null),
    direccion: "Av. Chapultepec 480, Piso 6, Guadalajara, Jal.",
    modelo: "Joy",
    duenoOriginalRegistrado: DUENO_ORIGINAL,
    contextoCompra: "contado",
    antiguedad: "normal",
    documentos: [
      docIdentificacion("doc-8-id", "Héctor Iván Ramírez Cuevas"),
      {
        id: "doc-8-esc",
        tipo: "escritura",
        nombreArchivo: "(pendiente — solicitada al usuario)",
        urlMock: "mock://doc/faltante",
        requerimiento: "pendiente",
        estado: "en_revision",
        vigencia: "no_aplica",
        datosExtraidos: {},
      },
      {
        id: "doc-8-curp",
        tipo: "curp_constancia",
        nombreArchivo: "Constancia_CURP.pdf",
        urlMock: "mock://doc/curp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: { curp: c("RACH930822HJCMVC03", "validado", "doc-8-curp") },
      },
    ],
    cruces: [
      {
        id: "x8-cad",
        etiqueta: "Cadena de dominio (enajenante escritura vs. dueño original SOZU)",
        resultado: "ambar",
        detalle: "No verificable aún: falta la escritura para comparar el enajenante.",
        esCadenaDominio: true,
      },
    ],
    semaforoAgregado: "ambar",
    gravamen: { existe: false, acreedor: null },
    verificacionRegistral: "no_iniciada",
    cadenaDominioConfirmada: null,
    estado: "info_solicitada",
    nivelSolicitado: 1,
    nivelOtorgado: null,
    areaAsignada: "administracion",
    fechaCreacion: "2026-07-09T13:00:00.000Z",
    diasEnCola: 5,
    auditoria: [
      { id: "a8-1", timestamp: "2026-07-09T13:00:00.000Z", usuario: "Sistema", accion: "Solicitud recibida", detalle: "Expediente inicial incompleto." },
      { id: "a8-2", timestamp: "2026-07-10T10:20:00.000Z", usuario: "C. Delgado (Administración)", accion: "Solicitó más documentación", detalle: "Se pidió la escritura pública. Notificado al solicitante." },
    ],
  },

  // 9) Aprobada Nivel 1 (terminal, auditoría poblada)
  {
    id: "TIT-000009",
    tipoPersona: "fisica",
    nombreODireccionRazonSocial: "Laura Beatriz Ortega Ríos",
    rfc: c("OERL890205G12", "validado", "doc-9-esc"),
    curp: c("OERL890205MJCRRR08", "validado", "doc-9-curp"),
    correo: "laura.ortega@gmail.com",
    telefono: "+52 33 9900 1122",
    desarrollo: "Margot",
    unidad: "#210",
    folioReal: c("9910044", "validado", "doc-9-esc"),
    direccion: "Av. Chapultepec 480, Piso 2, Guadalajara, Jal.",
    modelo: "Kind",
    duenoOriginalRegistrado: DUENO_ORIGINAL,
    contextoCompra: "contado",
    antiguedad: "normal",
    documentos: [
      docIdentificacion("doc-9-id", "Laura Beatriz Ortega Ríos"),
      {
        id: "doc-9-esc",
        tipo: "escritura",
        nombreArchivo: "Escritura_publica_45990.pdf",
        urlMock: "mock://doc/escritura",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: {
          adquiriente: c("Laura Beatriz Ortega Ríos", "validado", "doc-9-esc"),
          enajenante: c(DUENO_ORIGINAL, "validado", "doc-9-esc"),
        },
      },
      {
        id: "doc-9-curp",
        tipo: "curp_constancia",
        nombreArchivo: "Constancia_CURP.pdf",
        urlMock: "mock://doc/curp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: { curp: c("OERL890205MJCRRR08", "validado", "doc-9-curp") },
      },
    ],
    cruces: [
      {
        id: "x9-cad",
        etiqueta: "Cadena de dominio (enajenante escritura vs. dueño original SOZU)",
        resultado: "verde",
        detalle: "Enajenante = dueño original registrado.",
        esCadenaDominio: true,
      },
      { id: "x9-id", etiqueta: "Nombre ID = Escritura", resultado: "verde", detalle: "Coinciden." },
    ],
    semaforoAgregado: "verde",
    gravamen: { existe: false, acreedor: null },
    verificacionRegistral: "no_iniciada",
    cadenaDominioConfirmada: null,
    estado: "aprobada",
    nivelSolicitado: 1,
    nivelOtorgado: 1,
    areaAsignada: "administracion",
    fechaCreacion: "2026-06-30T10:00:00.000Z",
    diasEnCola: 0,
    auditoria: [
      { id: "a9-1", timestamp: "2026-06-30T10:00:00.000Z", usuario: "Sistema", accion: "Solicitud recibida", detalle: "Expediente con identificación y escritura." },
      { id: "a9-2", timestamp: "2026-07-01T11:30:00.000Z", usuario: "C. Delgado (Administración)", accion: "Validó identificación y escritura", detalle: "Match de propiedad confirmado." },
      { id: "a9-3", timestamp: "2026-07-01T11:45:00.000Z", usuario: "C. Delgado (Administración)", accion: "Aprobó Nivel 1", detalle: "Titularidad provisional para administración/cobro de mantenimiento; RPP aún no verificado." },
    ],
  },

  // 10) Rechazada con motivo (terminal, auditoría poblada)
  {
    id: "TIT-000010",
    tipoPersona: "fisica",
    nombreODireccionRazonSocial: "Fernando Aguilar Solís",
    rfc: c("AUSF800101H10", "rechazado", "doc-10-id"),
    curp: c("AUSF800101HJCGLR02", "validado", "doc-10-curp"),
    correo: "fernando.aguilar@gmail.com",
    telefono: "+52 33 1010 2020",
    desarrollo: "Margot",
    unidad: "#1201",
    folioReal: c("1055233", "rechazado", null),
    direccion: "Av. Chapultepec 480, Piso 12, Guadalajara, Jal.",
    modelo: "Soft",
    duenoOriginalRegistrado: DUENO_ORIGINAL,
    contextoCompra: "contado",
    antiguedad: "normal",
    documentos: [
      docIdentificacion("doc-10-id", "Fernando Aguilar Solís"),
      {
        id: "doc-10-esc",
        tipo: "escritura",
        nombreArchivo: "Documento_ilegible.pdf",
        urlMock: "mock://doc/escritura",
        requerimiento: "cargado",
        estado: "rechazado",
        vigencia: "no_aplica",
        datosExtraidos: {
          adquiriente: c(null, "rechazado", "doc-10-esc"),
        },
        motivoRechazo: "El documento no corresponde a una escritura pública de la unidad #1201.",
      },
      {
        id: "doc-10-curp",
        tipo: "curp_constancia",
        nombreArchivo: "Constancia_CURP.pdf",
        urlMock: "mock://doc/curp",
        requerimiento: "cargado",
        estado: "validado",
        vigencia: "no_aplica",
        datosExtraidos: { curp: c("AUSF800101HJCGLR02", "validado", "doc-10-curp") },
      },
    ],
    cruces: [
      {
        id: "x10-cad",
        etiqueta: "Cadena de dominio (enajenante escritura vs. dueño original SOZU)",
        resultado: "rojo",
        detalle: "No se pudo establecer: la escritura presentada no corresponde a la unidad.",
        esCadenaDominio: true,
      },
    ],
    semaforoAgregado: "rojo",
    gravamen: { existe: false, acreedor: null },
    verificacionRegistral: "no_verificable",
    cadenaDominioConfirmada: false,
    estado: "rechazada",
    nivelSolicitado: 2,
    nivelOtorgado: null,
    areaAsignada: "legal",
    motivoRechazo:
      "La escritura presentada no corresponde a la unidad #1201 de Margot. No se acredita la propiedad. Puede volver a solicitar con la documentación correcta.",
    fechaCreacion: "2026-07-03T15:00:00.000Z",
    diasEnCola: 0,
    auditoria: [
      { id: "a10-1", timestamp: "2026-07-03T15:00:00.000Z", usuario: "Sistema", accion: "Solicitud recibida", detalle: "Expediente con escritura ilegible." },
      { id: "a10-2", timestamp: "2026-07-04T09:10:00.000Z", usuario: "L. Ramírez (Legal)", accion: "Rechazó escritura", detalle: "Documento no corresponde a la unidad." },
      { id: "a10-3", timestamp: "2026-07-04T09:12:00.000Z", usuario: "L. Ramírez (Legal)", accion: "Rechazó solicitud", detalle: "Motivo notificado al solicitante." },
    ],
  },
];
