// Rutas válidas del sistema (deben coincidir con las rutas en src/App.tsx)
export const VALID_ADMIN_ROUTES = new Set([
  '/admin',
  '/admin/proyectos',
  '/admin/propiedades',
  '/admin/activos-comerciales',
  '/admin/activos-comerciales/nuevo',
  '/admin/activos-comerciales/:id',
  '/admin/activos-comerciales/:id/editar',
  '/admin/usuarios',
  '/admin/usuarios/nuevo',
  '/admin/usuarios-directivos',
  '/admin/usuarios-clientes',
  '/admin/roles-permisos',
  '/admin/entidades-legales',
  '/admin/desarrolladores',
  '/admin/inmobiliarias',
  '/admin/administradoras',
  '/admin/notarias',
  '/admin/bancos',
  '/admin/prospectos',
  '/admin/compradores',
  '/admin/vendedores',
  '/admin/duenos',
  '/admin/residentes',
  '/admin/agentes',
  '/admin/administradores-personas',
  '/admin/representantes-legales',
  '/admin/representantes-comerciales',
  '/admin/productos',
  '/admin/servicios',
  '/admin/categorias-productos',
  '/admin/amenidades',
  '/admin/caracteristicas',
  '/admin/modelos',
  '/admin/vistas',
  '/admin/estacionamientos',
  '/admin/bodegas',
  '/admin/cuentas-cobranza',
  '/admin/cuentas-mantenimiento',
  '/admin/comisiones',
  '/admin/aprobacion-comisiones',
  '/admin/comisiones-externas',
  '/admin/pagar-comisiones',
  '/admin/pago-proveedores',
  '/admin/pagos',
  '/admin/cuentas-bancarias',
  '/admin/documentos',
  '/admin/notarios/revision-documentacion',
  '/admin/consultas-ia',
  '/admin/reservas',
  '/admin/legal/contratos',
  '/admin/legal/carta-acuerdos',
  '/admin/reportes/discrepancias',
  '/admin/logs-actividad',
  '/admin/rastreo-clabes-stp',
  '/admin/rastreo-pagos-stp',
  '/admin/configuracion-reportes',
  '/admin/version-produccion',
  '/admin/reportes/inventarios',
  '/admin/reportes/finanzas',
  '/admin/reportes/ver/:id',
  '/admin/inmobiliarias/mi-informacion',
  '/admin/inmobiliarias/mis-agentes',
  '/admin/inmobiliarias/mis-propiedades',
  '/admin/inmobiliarias/mis-ventas',
  '/admin/inmobiliarias/proyectos',
  '/admin/inmobiliarias/proyectos/:id',
  '/admin/inmobiliarias/proyectos/:id/inventario',
  '/admin/inmobiliarias/inventario',
  '/admin/administrar-menus',
  '/admin/cuentas-mantenimiento/:id/detalle',
  '/admin/cuentas-cobranza/:id/detalle',
  '/admin/comunicacion/administrar-avisos',
  '/admin/comunicacion/enviar-avisos',
  '/admin/comunicacion/ejecuciones',
  '/admin/crm/workflow-ofertas',
  '/admin/crm/dashboard-ejecutivo',
  '/admin/mediciones-cta',
  '/admin/ab-tests',
  '/admin/comunicacion/configuracion-citas',
  '/admin/comunicacion/todas-las-citas',
  '/admin/agent/inicio',
  '/admin/agent/inventario',
  '/admin/agent/pipeline',
  '/admin/agent/comisiones',
  '/admin/agent/perfil',
  '/admin/agent/perfil/bloque/:id',
  // Portal Inmobiliaria
  '/admin/portal-inmobiliaria/dashboard',
  '/admin/portal-inmobiliaria/agentes',
  '/admin/portal-inmobiliaria/pipeline',
  '/admin/portal-inmobiliaria/prospectos',
  '/admin/portal-inmobiliaria/citas',
  '/admin/portal-inmobiliaria/comisiones',
  '/admin/portal-inmobiliaria/configuracion',
  '/admin/portal-inmobiliaria/agentes/:email',
  // Portal Cliente
  '/admin/portal-cliente/inicio',
  '/admin/portal-cliente/pagos',
  '/admin/portal-cliente/perfil',
  '/admin/notificaciones-config',
  '/admin/notificaciones-log',
  // Portal Cobranza
  '/admin/portal-cobranza/inmuebles',
  '/admin/portal-cobranza/complementos',
  '/admin/portal-cobranza/cuentas-cobranza',
  '/admin/portal-cobranza/atencion-clientes',
  '/admin/portal-cobranza/relacion-pagos',
  '/admin/portal-cobranza/ceps-pendientes',
  '/admin/portal-cobranza/conciliaciones',
  '/admin/portal-cobranza/promesas-pago',
  '/admin/portal-cobranza/comunicacion/avisos',
  '/admin/portal-cobranza/comunicacion/enviar',
  '/admin/portal-cobranza/comunicacion/ejecuciones',
  '/admin/portal-cobranza/comunicacion/plantillas',
  '/admin/portal-cobranza/reportes',
  // Portal Escrituración
  '/admin/portal-escrituracion/dashboard',
  '/admin/portal-escrituracion/expedientes',
  '/admin/portal-escrituracion/unidades',
  '/admin/portal-escrituracion/credito',
  '/admin/portal-escrituracion/pipeline',
  '/admin/portal-escrituracion/notarias',
  '/admin/portal-escrituracion/notarios',
  '/admin/portal-escrituracion/avaluos',
  '/admin/portal-escrituracion/pld',
  '/admin/portal-escrituracion/borradores',
  '/admin/portal-escrituracion/plantillas',
  '/admin/portal-escrituracion/firmas',
  '/admin/portal-escrituracion/citas',
  '/admin/portal-escrituracion/entregas',
  '/admin/portal-escrituracion/checklist-configuracion',
  '/admin/portal-escrituracion/rpp',
  '/admin/portal-escrituracion/reportes',
  '/admin/portal-escrituracion/auditoria',
  '/admin/portal-escrituracion/configuracion',
  // Portal Alta Dirección
  '/admin/portal-alta-direccion/dashboard',
  '/admin/portal-alta-direccion/citas',
  '/admin/portal-alta-direccion/prospectos',
  '/admin/portal-alta-direccion/pipeline',
  '/admin/portal-alta-direccion/ofertas',
  '/admin/portal-alta-direccion/cobranza',
  '/admin/portal-alta-direccion/contratos',
  '/admin/portal-alta-direccion/facturas',
  '/admin/portal-alta-direccion/comisiones',
  '/admin/portal-alta-direccion/red-comercial',
  '/admin/portal-alta-direccion/reportes',
  '/admin/portal-alta-direccion/auditoria',
  '/admin/portal-alta-direccion/configuracion',
  // Portal de Administración
  '/admin/portal-administracion/dashboard',
  '/admin/portal-administracion/citas',
  '/admin/portal-administracion/prospectos',
  '/admin/portal-administracion/pipeline',
  '/admin/portal-administracion/ofertas',
  '/admin/portal-administracion/cobranza',
  '/admin/portal-administracion/contratos',
  '/admin/portal-administracion/facturas',
  '/admin/portal-administracion/comisiones',
  '/admin/portal-administracion/red-comercial',
  '/admin/portal-administracion/reportes',
  '/admin/portal-administracion/auditoria',
  '/admin/portal-administracion/configuracion',
  '/admin/portal-administracion/notificaciones',
  '/admin/portal-administracion/bandeja',
  '/admin/portal-administracion/ciclo-venta',
  '/admin/portal-administracion/facturas-por-cobrar',
  '/admin/portal-administracion/facturas-por-pagar',
  '/admin/portal-administracion/comisiones-externas',
  '/admin/portal-administracion/comisiones-internas',
  // Portal Embajadores
  '/admin/embajadores/gestion',
  '/admin/portal-embajador/inicio',
  '/admin/portal-embajador/mis-referidos',
  '/admin/portal-embajador/registrar-referido',
  '/admin/portal-embajador/comisiones',
  '/admin/portal-embajador/perfil',
  // Portal CRM Sozu
  '/admin/portal-crm/dashboard',
  '/admin/portal-crm/alertas',
  '/admin/portal-crm/tracking-health',
  '/admin/portal-crm/conversion-events',
  '/admin/portal-crm/crm/contacts',
  '/admin/portal-crm/crm/contacts/:contactId',
  '/admin/portal-crm/crm/deals',
  '/admin/portal-crm/crm/appointments',
  '/admin/portal-crm/crm/tasks',
  '/admin/portal-crm/crm/sequences',
  '/admin/portal-crm/crm/routing',
  '/admin/portal-crm/crm/automation-rules',
  '/admin/portal-crm/crm/escalations',
  '/admin/portal-crm/crm/lead-intelligence',
  '/admin/portal-crm/crm/agent-performance',
  '/admin/portal-crm/crm/sales-operations',
  // Portal CRM Sozu — Inteligencia de marketing (Fase 3)
  '/admin/portal-crm/marketing/campaigns',
  '/admin/portal-crm/marketing/audiences',
  '/admin/portal-crm/marketing/attribution',
  '/admin/portal-crm/marketing/creatives',
  '/admin/portal-crm/marketing/utms',
  '/admin/portal-crm/marketing/ab-tests',
  '/admin/portal-crm/marketing/landing-pages',
  '/admin/portal-crm/marketing/forms',
  '/admin/portal-crm/marketing/integrations',
  '/admin/portal-crm/marketing/budget',
  // Portal CRM Sozu — Dirección · Inteligencia de ingresos (Fase 4)
  '/admin/portal-crm/revenue/executive-kpis',
  '/admin/portal-crm/revenue/forecast',
  '/admin/portal-crm/revenue/pipeline-review',
  '/admin/portal-crm/revenue/revenue-ops',
  '/admin/portal-crm/revenue/cohorts',
  '/admin/portal-crm/revenue/churn',
  '/admin/portal-crm/revenue/reporting',
  // Portal CRM Sozu — Operación (Fase 5)
  '/admin/portal-crm/operations/inbox',
  '/admin/portal-crm/operations/queues',
  '/admin/portal-crm/operations/sla',
  // Portal CRM Sozu — Configuración (Fase 6)
  '/admin/portal-crm/settings/users',
  '/admin/portal-crm/settings/roles',
  '/admin/portal-crm/settings/pipeline-stages',
  '/admin/portal-crm/settings/custom-fields',
  '/admin/portal-crm/settings/webhooks',
  '/admin/portal-crm/settings/connections/google/callback',
  '/admin/portal-crm/settings/connections/meta/callback',
  '/admin/portal-crm/settings/audit-log',
]);

export function isValidRoute(route: string): boolean {
  if (!route || !route.startsWith('/admin')) {
    return false;
  }
  
  // Buscar ruta exacta
  if (VALID_ADMIN_ROUTES.has(route)) {
    return true;
  }
  
  // Soporte para rutas parametrizadas (ej: /admin/reportes/ver/:id)
  // Normalizar la ruta entrante para comparar con patrones
  for (const validRoute of VALID_ADMIN_ROUTES) {
    if (validRoute.includes(':')) {
      // Convertir patrón a regex
      const pattern = validRoute.replace(/:\w+/g, '[^/]+');
      const regex = new RegExp(`^${pattern}$`);
      if (regex.test(route)) {
        return true;
      }
    }
  }
  
  return false;
}
