// Rutas válidas del sistema (deben coincidir con las rutas en src/App.tsx)
export const VALID_ADMIN_ROUTES = new Set([
  '/admin',
  '/admin/proyectos',
  '/admin/propiedades',
  '/admin/activos-comerciales',
  '/admin/activos-comerciales/nuevo',
  '/admin/activos-comerciales/:id',
  '/admin/activos-comerciales/:id/editar',
  '/admin/usuarios',
  '/admin/usuarios/nuevo',
  '/admin/usuarios-directivos',
  '/admin/usuarios-clientes',
  '/admin/roles-permisos',
  '/admin/entidades-legales',
  '/admin/desarrolladores',
  '/admin/inmobiliarias',
  '/admin/administradoras',
  '/admin/notarias',
  '/admin/bancos',
  '/admin/prospectos',
  '/admin/compradores',
  '/admin/vendedores',
  '/admin/duenos',
  '/admin/residentes',
  '/admin/agentes',
  '/admin/administradores-personas',
  '/admin/representantes-legales',
  '/admin/representantes-comerciales',
  '/admin/productos',
  '/admin/servicios',
  '/admin/categorias-productos',
  '/admin/amenidades',
  '/admin/caracteristicas',
  '/admin/modelos',
  '/admin/vistas',
  '/admin/estacionamientos',
  '/admin/bodegas',
  '/admin/cuentas-cobranza',
  '/admin/cuentas-mantenimiento',
  '/admin/comisiones',
  '/admin/aprobacion-comisiones',
  '/admin/comisiones-externas',
  '/admin/pagar-comisiones',
  '/admin/pago-proveedores',
  '/admin/pagos',
  '/admin/cuentas-bancarias',
  '/admin/documentos',
  '/admin/notarios/revision-documentacion',
  '/admin/consultas-ia',
  '/admin/reservas',
  '/admin/legal/contratos',
  '/admin/legal/carta-acuerdos',
  '/admin/reportes/discrepancias',
  '/admin/logs-actividad',
  '/admin/rastreo-clabes-stp',
  '/admin/rastreo-pagos-stp',
  '/admin/configuracion-reportes',
  '/admin/version-produccion',
  '/admin/reportes/inventarios',
  '/admin/reportes/finanzas',
  '/admin/reportes/ver/:id',
  '/admin/inmobiliarias/mi-informacion',
  '/admin/inmobiliarias/mis-agentes',
  '/admin/inmobiliarias/mis-propiedades',
  '/admin/inmobiliarias/mis-ventas',
  '/admin/inmobiliarias/proyectos',
  '/admin/inmobiliarias/proyectos/:id',
  '/admin/inmobiliarias/proyectos/:id/inventario',
  '/admin/inmobiliarias/inventario',
  '/admin/administrar-menus',
  '/admin/cuentas-mantenimiento/:id/detalle',
  '/admin/cuentas-cobranza/:id/detalle',
  '/admin/comunicacion/administrar-avisos',
  '/admin/comunicacion/enviar-avisos',
  '/admin/comunicacion/ejecuciones',
  '/admin/crm/workflow-ofertas',
  '/admin/crm/dashboard-ejecutivo',
  '/admin/mediciones-cta',
  '/admin/ab-tests',
  '/admin/comunicacion/configuracion-citas',
  '/admin/comunicacion/todas-las-citas',
  '/admin/agent/inicio',
  '/admin/agent/inventario',
  '/admin/agent/pipeline',
  '/admin/agent/comisiones',
  '/admin/agent/perfil',
  '/admin/agent/perfil/bloque/:id',
  // Portal Inmobiliaria
  '/admin/portal-inmobiliaria/dashboard',
  '/admin/portal-inmobiliaria/agentes',
  '/admin/portal-inmobiliaria/pipeline',
  '/admin/portal-inmobiliaria/prospectos',
  '/admin/portal-inmobiliaria/citas',
  '/admin/portal-inmobiliaria/comisiones',
  '/admin/portal-inmobiliaria/configuracion',
  '/admin/portal-inmobiliaria/agentes/:email',
  // Portal Cliente
  '/admin/portal-cliente/inicio',
  '/admin/portal-cliente/pagos',
  '/admin/portal-cliente/perfil',
  '/admin/notificaciones-config',
  '/admin/notificaciones-log',
  // Portal Cobranza
  '/admin/portal-cobranza/inmuebles',
  '/admin/portal-cobranza/complementos',
  '/admin/portal-cobranza/cuentas-cobranza',
  '/admin/portal-cobranza/atencion-clientes',
  '/admin/portal-cobranza/relacion-pagos',
  '/admin/portal-cobranza/ceps-pendientes',
  '/admin/portal-cobranza/conciliaciones',
  '/admin/portal-cobranza/promesas-pago',
  '/admin/portal-cobranza/comunicacion/avisos',
  '/admin/portal-cobranza/comunicacion/enviar',
  '/admin/portal-cobranza/comunicacion/ejecuciones',
  '/admin/portal-cobranza/comunicacion/plantillas',
  '/admin/portal-cobranza/reportes',
  // Portal Escrituración
  '/admin/portal-escrituracion/dashboard',
  '/admin/portal-escrituracion/expedientes',
  '/admin/portal-escrituracion/unidades-listas-escriturar',
  '/admin/portal-escrituracion/unidades',
  '/admin/portal-escrituracion/credito',
  '/admin/portal-escrituracion/pipeline',
  '/admin/portal-escrituracion/notarias',
  '/admin/portal-escrituracion/notarios',
  '/admin/portal-escrituracion/avaluos',
  '/admin/portal-escrituracion/pld',
  '/admin/portal-escrituracion/borradores',
  '/admin/portal-escrituracion/plantillas',
  '/admin/portal-escrituracion/firmas',
  '/admin/portal-escrituracion/citas',
  '/admin/portal-escrituracion/entregas',
  '/admin/portal-escrituracion/checklist-configuracion',
  '/admin/portal-escrituracion/rpp',
  '/admin/portal-escrituracion/reportes',
  '/admin/portal-escrituracion/auditoria',
  '/admin/portal-escrituracion/configuracion',
  // Portal Alta Dirección
  '/admin/portal-alta-direccion/dashboard',
  '/admin/portal-alta-direccion/citas',
  '/admin/portal-alta-direccion/prospectos',
  '/admin/portal-alta-direccion/pipeline',
  '/admin/portal-alta-direccion/ofertas',
  '/admin/portal-alta-direccion/cobranza',
  '/admin/portal-alta-direccion/contratos',
  '/admin/portal-alta-direccion/facturas',
  '/admin/portal-alta-direccion/comisiones',
  '/admin/portal-alta-direccion/red-comercial',
  '/admin/portal-alta-direccion/reportes',
  '/admin/portal-alta-direccion/auditoria',
  '/admin/portal-alta-direccion/configuracion',
  // Portal de Administración
  '/admin/portal-administracion/dashboard',
  '/admin/portal-administracion/citas',
  '/admin/portal-administracion/prospectos',
  '/admin/portal-administracion/pipeline',
  '/admin/portal-administracion/ofertas',
  '/admin/portal-administracion/cobranza',
  '/admin/portal-administracion/contratos',
  '/admin/portal-administracion/facturas',
  '/admin/portal-administracion/comisiones',
  '/admin/portal-administracion/red-comercial',
  '/admin/portal-administracion/reportes',
  '/admin/portal-administracion/auditoria',
  '/admin/portal-administracion/configuracion',
  '/admin/portal-administracion/notificaciones',
  '/admin/portal-administracion/bandeja',
  '/admin/portal-administracion/ciclo-venta',
  '/admin/portal-administracion/facturas-por-cobrar',
  '/admin/portal-administracion/facturas-por-pagar',
  '/admin/portal-administracion/comisiones-externas',
  '/admin/portal-administracion/comisiones-internas',
  // Portal Embajadores
  '/admin/embajadores/gestion',
  '/admin/portal-embajador/inicio',
  '/admin/portal-embajador/mis-referidos',
  '/admin/portal-embajador/registrar-referido',
  '/admin/portal-embajador/comisiones',
  '/admin/portal-embajador/perfil',
  // Portal CRM Sozu — Resumen / Tracking
  '/admin/portal-crm/dashboard',
  '/admin/portal-crm/alertas',
  '/admin/portal-crm/salud-tracking',
  '/admin/portal-crm/eventos-conversion',
  // Portal CRM Sozu — Dirección
  '/admin/portal-crm/direccion/dashboard',
  '/admin/portal-crm/direccion/cola-decisiones',
  '/admin/portal-crm/direccion/resumen-semanal',
  // Portal CRM Sozu — CRM / Ventas
  '/admin/portal-crm/ventas/contactos',
  '/admin/portal-crm/ventas/contactos/:contactId',
  '/admin/portal-crm/ventas/negocios',
  '/admin/portal-crm/ventas/negocios/:dealId',
  '/admin/portal-crm/ventas/tareas',
  '/admin/portal-crm/ventas/citas',
  '/admin/portal-crm/ventas/rendimiento-asesores',
  '/admin/portal-crm/ventas/inteligencia-prospectos',
  '/admin/portal-crm/ventas/asignacion',
  '/admin/portal-crm/ventas/operacion-comercial',
  '/admin/portal-crm/ventas/reglas-automatizacion',
  '/admin/portal-crm/ventas/secuencias',
  '/admin/portal-crm/ventas/escalamientos',
  // Portal CRM Sozu — Inteligencia de marketing
  '/admin/portal-crm/marketing/rendimiento',
  '/admin/portal-crm/marketing/atribucion',
  '/admin/portal-crm/marketing/campanas',
  '/admin/portal-crm/marketing/creativos',
  '/admin/portal-crm/marketing/meta',
  '/admin/portal-crm/marketing/google',
  '/admin/portal-crm/marketing/desarrollos',
  '/admin/portal-crm/marketing/embudo',
  '/admin/portal-crm/marketing/mapeo-campanas',
  '/admin/portal-crm/marketing/sincronizaciones',
  '/admin/portal-crm/marketing/audiencias',
  '/admin/portal-crm/marketing/utms',
  '/admin/portal-crm/marketing/pruebas-ab',
  '/admin/portal-crm/marketing/paginas-aterrizaje',
  '/admin/portal-crm/marketing/formularios',
  '/admin/portal-crm/marketing/integraciones',
  '/admin/portal-crm/marketing/presupuesto',
  // Portal CRM Sozu — Inteligencia de ingresos
  '/admin/portal-crm/ingresos/pronostico',
  '/admin/portal-crm/ingresos/atribucion',
  '/admin/portal-crm/ingresos/velocidad',
  '/admin/portal-crm/ingresos/metas',
  '/admin/portal-crm/ingresos/kpis-ejecutivos',
  '/admin/portal-crm/ingresos/revision-pipeline',
  '/admin/portal-crm/ingresos/operaciones',
  '/admin/portal-crm/ingresos/cohortes',
  '/admin/portal-crm/ingresos/desercion',
  '/admin/portal-crm/ingresos/reportes',
  // Portal CRM Sozu — Operación
  '/admin/portal-crm/operacion/constructor',
  '/admin/portal-crm/operacion/copiloto',
  '/admin/portal-crm/operacion/desarrollos',
  '/admin/portal-crm/operacion/bandeja',
  '/admin/portal-crm/operacion/colas',
  '/admin/portal-crm/operacion/sla',
  // Portal CRM Sozu — Configuración
  '/admin/portal-crm/configuracion/conexiones',
  '/admin/portal-crm/configuracion/preparacion-despliegue',
  '/admin/portal-crm/configuracion/registros-api',
  '/admin/portal-crm/configuracion/checklist-integracion',
  '/admin/portal-crm/configuracion/organizacion',
  '/admin/portal-crm/configuracion/usuarios',
  '/admin/portal-crm/configuracion/desarrollos',
  '/admin/portal-crm/configuracion/pipelines',
  '/admin/portal-crm/configuracion/estados-lead',
  '/admin/portal-crm/configuracion/roles',
  '/admin/portal-crm/configuracion/etapas-pipeline',
  '/admin/portal-crm/configuracion/campos-personalizados',
  '/admin/portal-crm/configuracion/webhooks',
  '/admin/portal-crm/configuracion/conexiones/google/callback',
  '/admin/portal-crm/configuracion/conexiones/meta/callback',
  '/admin/portal-crm/configuracion/auditoria',
]);

export function isValidRoute(route: string): boolean {
  if (!route || !route.startsWith('/admin')) {
    return false;
  }
  
  // Buscar ruta exacta
  if (VALID_ADMIN_ROUTES.has(route)) {
    return true;
  }
  
  // Soporte para rutas parametrizadas (ej: /admin/reportes/ver/:id)
  // Normalizar la ruta entrante para comparar con patrones
  for (const validRoute of VALID_ADMIN_ROUTES) {
    if (validRoute.includes(':')) {
      // Convertir patrón a regex
      const pattern = validRoute.replace(/:\w+/g, '[^/]+');
      const regex = new RegExp(`^${pattern}$`);
      if (regex.test(route)) {
        return true;
      }
    }
  }
  
  return false;
}
