-- Create estatus_proyecto table
CREATE TABLE public.estatus_proyecto (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  fecha_creacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Insert initial data for estatus_proyecto
INSERT INTO public.estatus_proyecto (nombre) VALUES 
('Preparación'),
('Demolición'),
('Excavación'),
('Muros'),
('Sótanos'),
('Planta Baja'),
('Primeros Niveles'),
('Niveles Medios'),
('Ultimos Niveles'),
('Fachada'),
('Interiores'),
('Detalles'),
('Finalizado');

-- Add new fields to proyectos table
ALTER TABLE public.proyectos 
ADD COLUMN id_estatus_proyecto integer REFERENCES public.estatus_proyecto(id),
ADD COLUMN fecha_lanzamiento timestamp without time zone,
ADD COLUMN fecha_entrega timestamp without time zone,
ADD COLUMN direccion_id_pais text REFERENCES public.paises(id),
ADD COLUMN direccion_id_estado integer REFERENCES public.estados_mx(id),
ADD COLUMN direccion_id_municipio integer REFERENCES public.municipios_mx(id);

-- Create trigger for estatus_proyecto updated_at
CREATE TRIGGER update_estatus_proyecto_updated_at
  BEFORE UPDATE ON public.estatus_proyecto
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();