-- Tabla para asignar planos arquitectónicos por edificio-modelo y piso
CREATE TABLE public.modelos_planos_arquitectonicos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_edificio_modelo BIGINT NOT NULL REFERENCES public.edificios_modelos(id) ON DELETE CASCADE,
  nivel INTEGER NOT NULL,
  imagen_url TEXT NOT NULL,
  storage_path TEXT,
  nombre_original TEXT NOT NULL,
  departamentos JSONB NOT NULL DEFAULT '[]'::jsonb,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT modelos_planos_arquitectonicos_nivel_check CHECK (nivel > 0),
  CONSTRAINT modelos_planos_arquitectonicos_departamentos_array_check CHECK (jsonb_typeof(departamentos) = 'array')
);

CREATE INDEX idx_modelos_planos_arquitectonicos_edificio_modelo
  ON public.modelos_planos_arquitectonicos (id_edificio_modelo);

CREATE INDEX idx_modelos_planos_arquitectonicos_nivel
  ON public.modelos_planos_arquitectonicos (nivel);

CREATE INDEX idx_modelos_planos_arquitectonicos_activo
  ON public.modelos_planos_arquitectonicos (activo);

CREATE UNIQUE INDEX uq_modelos_planos_arquitectonicos_activo_por_nivel
  ON public.modelos_planos_arquitectonicos (id_edificio_modelo, nivel, imagen_url)
  WHERE activo = true;

ALTER TABLE public.modelos_planos_arquitectonicos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view model floor plans"
ON public.modelos_planos_arquitectonicos
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated users can insert model floor plans"
ON public.modelos_planos_arquitectonicos
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Authenticated users can update model floor plans"
ON public.modelos_planos_arquitectonicos
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can delete model floor plans"
ON public.modelos_planos_arquitectonicos
FOR DELETE
TO authenticated
USING (true);

CREATE OR REPLACE FUNCTION public.update_modelos_planos_arquitectonicos_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_modelos_planos_arquitectonicos_updated_at
BEFORE UPDATE ON public.modelos_planos_arquitectonicos
FOR EACH ROW
EXECUTE FUNCTION public.update_modelos_planos_arquitectonicos_updated_at();